# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a5fc75e28e9b9bdf026057c8e5c15bc323d028f35f037adda6391170d9fe0348847cf2a02990fc018403cf5372d5c4b1fd9551aa71c11e967d8cc8186688427

test:
  secret_key_base: 25d8fe04c63648564eee39538be77dc5a945e717c8ce9968afaa77806b9160742abca9c45d833e4dc6d3001b353d0a300b06d3f551ac45168386ab7fdb3838b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
